### ISSUE TITLE
headers fails if first header is numeric (e.g. with AWS Cognito and other OAuth)

### ISSUE THREAD

**Issue by nealeu** [serviejs/servie#26] opened 2019-07-16 13:17 UTC
See https://github.com/mulesoft/js-client-oauth2/issues/119

```
/Projects/myapp/node_modules/servie/src/headers.ts:25
      this.object[key] = typeof value === "string" ? value : value.map(String);
                                                                   ^
TypeError: value.map is not a function
    at Headers.append (/Projects/myapp/node_modules/servie/src/headers.ts:25:68)
    at Headers.extend (/Projects/myapp/node_modules/servie/src/headers.ts:89:39)
    at new Headers (/Projects/myapp/node_modules/servie/src/headers.ts:12:20)
    at getDefaultHeaders (/Projects/myapp/node_modules/servie/src/node.ts:252:19)
    at new Response (/Projects/myapp/node_modules/servie/src/node.ts:215:21)
```

**Comment by GuillaumeLachaud** [comment] 2019-07-20 21:55
Having the same error trying to use Segment Oauth. Issue happens on `4.2.5`. Reverting back to `4.2.3` solves the issue.

**Comment by blakeembrey** [comment] 2019-08-01 00:27
The signature is designed explicitly to only accept strings, this was a feature and not a bug, but I'll take a look at fixing this here. They probably should not have blindly upgraded two major versions, a lot changed :smile:

**Comment by blakeembrey** [comment] 2019-08-01 00:33
Thanks for the report. I initially misunderstood the issue, taking a look at why we're getting numeric HTTP responses - it sounds like maybe something changed or I've missed something in the HTTP2 API.

**Comment by blakeembrey** [comment] 2019-08-01 01:53
Closing with https://github.com/serviejs/servie/pull/27. Sorry for the delay, I never saw this issue in my inbox until the PR was opened.

**Closed by blakeembrey** 2019-08-01 01:53 UTC
